# Temp Control Dial
DIAL_CLK_PIN = 14
DIAL_DT_PIN = 15
DIAL_SW_PIN = 8
DIAL_RES = 1 # Percent per click

# Status LEDs
GREEN_LED_PIN = 24
RED_LED_PIN = 25
STEADY_STATE_THRESH = 1, 1 # Volts, Amps

# System Temp Control
COOLING_RELAY_PIN = 1
COOLING_TEMP_PIN = 26
ZVS_TEMP_PIN = 27
MAX_ZVS_TEMP = 85 # Celsius
MAX_ZVS_SUPPLY_TEMP = 85 # Celsius
MAX_COOLANT_TEMP = 60 # Celsius
